export interface Component {
  name: string;
  slug: string;
  category: string;
  isNew: boolean;
}

export const components: Component[] = [
  // Form Controls
  {
    name: "Accordion",
    slug: "accordion",
    category: "Disclosure",
    isNew: false,
  },
  {
    name: "Angle Slider",
    slug: "angle-slider",
    category: "Form",
    isNew: true,
  },
  {
    name: "Avatar",
    slug: "avatar",
    category: "Data Display",
    isNew: false,
  },
  {
    name: "Carousel",
    slug: "carousel",
    category: "Data Display",
    isNew: true,
  },
  {
    name: "Checkbox",
    slug: "checkbox",
    category: "Form",
    isNew: false,
  },
  {
    name: "Clipboard",
    slug: "clipboard",
    category: "Utility",
    isNew: true,
  },
  {
    name: "Collapsible",
    slug: "collapsible",
    category: "Disclosure",
    isNew: false,
  },
  {
    name: "Color Picker",
    slug: "color-picker",
    category: "Form",
    isNew: true,
  },
  {
    name: "Combobox",
    slug: "combobox",
    category: "Form",
    isNew: false,
  },
  {
    name: "Date Picker",
    slug: "date-picker",
    category: "Form",
    isNew: true,
  },
  {
    name: "Dialog",
    slug: "dialog",
    category: "Overlay",
    isNew: false,
  },
  {
    name: "Editable",
    slug: "editable",
    category: "Form",
    isNew: true,
  },
  {
    name: "Field",
    slug: "field",
    category: "Form",
    isNew: false,
  },
  {
    name: "Fieldset",
    slug: "fieldset",
    category: "Form",
    isNew: false,
  },
  {
    name: "File Upload",
    slug: "file-upload",
    category: "Form",
    isNew: true,
  },
  {
    name: "Floating Panel",
    slug: "floating-panel",
    category: "Overlay",
    isNew: true,
  },
  {
    name: "Hover Card",
    slug: "hover-card",
    category: "Overlay",
    isNew: false,
  },
  {
    name: "Listbox",
    slug: "listbox",
    category: "Form",
    isNew: false,
  },
  {
    name: "Menu",
    slug: "menu",
    category: "Navigation",
    isNew: false,
  },
  {
    name: "Number Input",
    slug: "number-input",
    category: "Form",
    isNew: false,
  },
  {
    name: "Pagination",
    slug: "pagination",
    category: "Navigation",
    isNew: false,
  },
  {
    name: "Password Input",
    slug: "password-input",
    category: "Form",
    isNew: false,
  },
  {
    name: "Pin Input",
    slug: "pin-input",
    category: "Form",
    isNew: true,
  },
  {
    name: "Popover",
    slug: "popover",
    category: "Overlay",
    isNew: false,
  },
  {
    name: "Progress - Circular",
    slug: "progress-circular",
    category: "Feedback",
    isNew: false,
  },
  {
    name: "Progress - Linear",
    slug: "progress-linear",
    category: "Feedback",
    isNew: false,
  },
  {
    name: "QR Code",
    slug: "qr-code",
    category: "Data Display",
    isNew: true,
  },
  {
    name: "Radio Group",
    slug: "radio-group",
    category: "Form",
    isNew: false,
  },
  {
    name: "Rating Group",
    slug: "rating-group",
    category: "Form",
    isNew: true,
  },
  {
    name: "Segment Group",
    slug: "segment-group",
    category: "Form",
    isNew: false,
  },
  {
    name: "Select",
    slug: "select",
    category: "Form",
    isNew: false,
  },
  {
    name: "Signature Pad",
    slug: "signature-pad",
    category: "Form",
    isNew: true,
  },
  {
    name: "Slider",
    slug: "slider",
    category: "Form",
    isNew: false,
  },
  {
    name: "Splitter",
    slug: "splitter",
    category: "Layout",
    isNew: true,
  },
  {
    name: "Steps",
    slug: "steps",
    category: "Navigation",
    isNew: false,
  },
  {
    name: "Switch",
    slug: "switch",
    category: "Form",
    isNew: false,
  },
  {
    name: "Tabs",
    slug: "tabs",
    category: "Navigation",
    isNew: false,
  },
  {
    name: "Tags Input",
    slug: "tags-input",
    category: "Form",
    isNew: true,
  },
  {
    name: "Timer",
    slug: "timer",
    category: "Data Display",
    isNew: true,
  },
  {
    name: "Toast",
    slug: "toast",
    category: "Feedback",
    isNew: false,
  },
  {
    name: "Toggle Group",
    slug: "toggle-group",
    category: "Form",
    isNew: false,
  },
  {
    name: "Toggle",
    slug: "toggle",
    category: "Form",
    isNew: false,
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    category: "Overlay",
    isNew: false,
  },
  {
    name: "Tour",
    slug: "tour",
    category: "Overlay",
    isNew: true,
  },
  {
    name: "Tree View",
    slug: "tree-view",
    category: "Data Display",
    isNew: false,
  },
];
